name: Build and Deploy to AKS

on: 
  push:
    branches:
      - master
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USR }}
        password: ${{ secrets.DOCKER_PASS }}
    
    - name: build and tag image
      run: |
        IMAGE_TAG="${GITHUB_SHA}"
                IMAGE="${{ secrets.DOCKER_USR }}/php-web:$IMAGE_TAG"
                docker build -t $IMAGE .
        
    - name: push docker image
      run: |
        IMAGE_TAG="${GITHUB_SHA}"
        IMAGE="${{ secrets.DOCKER_USR }}/php-web:$IMAGE_TAG"
        docker push $IMAGE

    - name: Log in to Azure
      run: |
        az login --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group demo_AKS --name demo_AKS1 --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl apply -f ./k8s/php.yaml 
        kubectl apply -f ./k8s/php-service.yaml 

    - name: Update image in Kubernetes deployment
      run: |
        kubectl set image deployment/php-web php-web-container=${{ secrets.DOCKER_USR }}/php-web:${GITHUB_SHA}
        kubectl rollout status deployment/php-web 

    - name: Restart Pods to Ensure Changes are Applied
      run: |
        kubectl rollout restart deployment/php-web
        kubectl rollout status deployment/php-web  
